"use strict";

/* 
const request1 = new XMLHttpRequest();
const img = document.querySelector("img");
let yo;
let teamKey;
let playerID;
request1.open("GET", "https://api.sportsdata.io/v3/nfl/scores/json/TeamsBasic?key=ffb7852aadbe4662a351fad874b411ce");

request1.send();

request1.addEventListener("load", function () {
  const data = JSON.parse(this.responseText);
  console.log(data);

teamKey = data.filter((team) => team.Key === "ATL")[0].Key;
console.log(teamKey);
  img.src = data[0].PhotoUrl;
  console.log(img.src);
  const request2 = new XMLHttpRequest();
  request2.open(
    "GET",
    `https://api.sportsdata.io/v3/nfl/scores/json/PlayersBasic/${teamKey}?key=ffb7852aadbe4662a351fad874b411ce`
  );
  request2.send();
  request2.addEventListener("load", function () {
    const data2 = JSON.parse(this.responseText);
    console.log(data2);
    playerID = data2.filter((player) => player.Name === "Drake London")[0].PlayerID;
    console.log(playerID);
    const request3 = new XMLHttpRequest();
    request3.open(
      "GET",
      `https://api.sportsdata.io/v3/nfl/scores/json/Player/${playerID}?key=ffb7852aadbe4662a351fad874b411ce`
    );
    request3.send();
    request3.addEventListener("load", function () {
      const data3 = JSON.parse(this.responseText);
      console.log(data3);
    });
  });
});
 */

const teams = [
  {
    Key: "ARI",
    TeamID: 1,
    PlayerID: 1,
    City: "Arizona",
    Name: "Cardinals",
    Conference: "NFC",
    Division: "West",
    FullName: "Arizona Cardinals",
    StadiumID: 29,
    ByeWeek: 14,
    GlobalTeamID: 1,
    HeadCoach: "Jonathan Gannon",
    PrimaryColor: "97233F",
    SecondaryColor: "FFFFFF",
    TertiaryColor: "000000",
    QuaternaryColor: "A5ACAF",
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/0/04/Arizona_Cardinals_wordmark.svg",
    OffensiveCoordinator: "Drew Petzing",
    DefensiveCoordinator: "Nick Rallis",
    SpecialTeamsCoach: "Jeff Rodgers",
    OffensiveScheme: "3WR",
    DefensiveScheme: "3-4"
  },
  {
    Key: "ATL",
    TeamID: 2,
    PlayerID: 2,
    City: "Atlanta",
    Name: "Falcons",
    Conference: "NFC",
    Division: "South",
    FullName: "Atlanta Falcons",
    StadiumID: 45,
    ByeWeek: 11,
    GlobalTeamID: 2,
    HeadCoach: "Arthur Smith",
    PrimaryColor: "000000",
    SecondaryColor: "A71930",
    TertiaryColor: "A5ACAF",
    QuaternaryColor: "FFFFFF",
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Atlanta_Falcons_wordmark.svg",
    OffensiveCoordinator: "Dave Ragone",
    DefensiveCoordinator: "Ryan Nielsen",
    SpecialTeamsCoach: "Marquice Williams",
    OffensiveScheme: "3WR",
    DefensiveScheme: "3-4"
  },
  {
    Key: "BAL",
    TeamID: 3,
    PlayerID: 36,
    City: "Baltimore",
    Name: "Ravens",
    Conference: "AFC",
    Division: "North",
    FullName: "Baltimore Ravens",
    StadiumID: 7,
    ByeWeek: 13,
    GlobalTeamID: 3,
    HeadCoach: "John Harbaugh",
    PrimaryColor: "24135F",
    SecondaryColor: "000000",
    TertiaryColor: "9A7611",
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/1/16/Baltimore_Ravens_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Baltimore_Ravens_wordmark.svg",
    OffensiveCoordinator: "Todd Monken",
    DefensiveCoordinator: "Mike Macdonald",
    SpecialTeamsCoach: "Chris Horton",
    OffensiveScheme: "3WR",
    DefensiveScheme: "3-4"
  },
  {
    Key: "BUF",
    TeamID: 4,
    PlayerID: 37,
    City: "Buffalo",
    Name: "Bills",
    Conference: "AFC",
    Division: "East",
    FullName: "Buffalo Bills",
    StadiumID: 1,
    ByeWeek: 13,
    GlobalTeamID: 4,
    HeadCoach: "Sean McDermott",
    PrimaryColor: "00338D",
    SecondaryColor: "C60C30",
    TertiaryColor: "FFFFFF",
    QuaternaryColor: "00274D",
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Buffalo_Bills_wordmark.svg",
    OffensiveCoordinator: "Ken Dorsey",
    DefensiveCoordinator: null,
    SpecialTeamsCoach: "Matthew Smiley",
    OffensiveScheme: "3WR",
    DefensiveScheme: "4-3"
  },
  {
    Key: "CAR",
    TeamID: 5,
    PlayerID: 5,
    City: "Carolina",
    Name: "Panthers",
    Conference: "NFC",
    Division: "South",
    FullName: "Carolina Panthers",
    StadiumID: 26,
    ByeWeek: 7,
    GlobalTeamID: 5,
    HeadCoach: "Frank Reich",
    PrimaryColor: "000000",
    SecondaryColor: "0085CA",
    TertiaryColor: "BFC0BF",
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Carolina_Panthers_wordmark.svg",
    OffensiveCoordinator: "Thomas Brown",
    DefensiveCoordinator: "Ejiro Evero",
    SpecialTeamsCoach: "Chris Tabor",
    OffensiveScheme: "3WR",
    DefensiveScheme: "3-4"
  },
  {
    Key: "CHI",
    TeamID: 6,
    PlayerID: 38,
    City: "Chicago",
    Name: "Bears",
    Conference: "NFC",
    Division: "North",
    FullName: "Chicago Bears",
    StadiumID: 20,
    ByeWeek: 13,
    GlobalTeamID: 6,
    HeadCoach: "Matt Eberflus",
    PrimaryColor: "0B162A",
    SecondaryColor: "E64100",
    TertiaryColor: "FFFFFF",
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Chicago_Bears_wordmark.svg",
    OffensiveCoordinator: "Luke Getsy",
    DefensiveCoordinator: "Alan Williams",
    SpecialTeamsCoach: "Richard Hightower",
    OffensiveScheme: "3WR",
    DefensiveScheme: "4-3"
  },
  {
    Key: "CIN",
    TeamID: 7,
    PlayerID: 7,
    City: "Cincinnati",
    Name: "Bengals",
    Conference: "AFC",
    Division: "North",
    FullName: "Cincinnati Bengals",
    StadiumID: 5,
    ByeWeek: 7,
    GlobalTeamID: 7,
    HeadCoach: "Zac Taylor",
    PrimaryColor: "000000",
    SecondaryColor: "FB4F14",
    TertiaryColor: "FFFFFF",
    QuaternaryColor: "",
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Cincinnati_Bengals_wordmark.svg",
    OffensiveCoordinator: "Brian Callahan",
    DefensiveCoordinator: "Lou Anarumo",
    SpecialTeamsCoach: "Darrin Simmons",
    OffensiveScheme: "3WR",
    DefensiveScheme: "4-3"
  },
  {
    Key: "CLE",
    TeamID: 8,
    PlayerID: 8,
    City: "Cleveland",
    Name: "Browns",
    Conference: "AFC",
    Division: "North",
    FullName: "Cleveland Browns",
    StadiumID: 6,
    ByeWeek: 5,
    GlobalTeamID: 8,
    HeadCoach: "Kevin Stefanski",
    PrimaryColor: "311D00",
    SecondaryColor: "FF3300",
    TertiaryColor: "FFFFFF",
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Cleveland_Browns_wordmark.svg",
    OffensiveCoordinator: "Alex Van Pelt",
    DefensiveCoordinator: "Jim Schwartz",
    SpecialTeamsCoach: "Bubba Ventrone",
    OffensiveScheme: "3WR",
    DefensiveScheme: "4-3"
  },
  {
    Key: "DAL",
    TeamID: 9,
    PlayerID: 48,
    City: "Dallas",
    Name: "Cowboys",
    Conference: "NFC",
    Division: "East",
    FullName: "Dallas Cowboys",
    StadiumID: 17,
    ByeWeek: 7,
    GlobalTeamID: 9,
    HeadCoach: "Mike McCarthy",
    PrimaryColor: "002244",
    SecondaryColor: "B0B7BC",
    TertiaryColor: "00338D",
    QuaternaryColor: "FFFFFF",
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/b/be/Cowboys_wordmark.svg",
    OffensiveCoordinator: "Brian Schottenheimer",
    DefensiveCoordinator: "Dan Quinn",
    SpecialTeamsCoach: "John Fassel",
    OffensiveScheme: "3WR",
    DefensiveScheme: "4-3"
  },
  {
    Key: "DEN",
    TeamID: 10,
    PlayerID: 49,
    City: "Denver",
    Name: "Broncos",
    Conference: "AFC",
    Division: "West",
    FullName: "Denver Broncos",
    StadiumID: 13,
    ByeWeek: 9,
    GlobalTeamID: 10,
    HeadCoach: "Sean Payton",
    PrimaryColor: "FC4C02",
    SecondaryColor: "0A2343",
    TertiaryColor: "FFFFFF",
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg",
    WikipediaWordMarkURL:
      "https://upload.wikimedia.org/wikipedia/commons/c/c4/Denver_Broncos_wordmark_%28c._1997%29.png",
    OffensiveCoordinator: "Joe Lombardi",
    DefensiveCoordinator: "Vance Joseph",
    SpecialTeamsCoach: "Ben Kotwica",
    OffensiveScheme: "3WR",
    DefensiveScheme: "3-4"
  },
  {
    Key: "DET",
    TeamID: 11,
    PlayerID: 11,
    City: "Detroit",
    Name: "Lions",
    Conference: "NFC",
    Division: "North",
    FullName: "Detroit Lions",
    StadiumID: 21,
    ByeWeek: 9,
    GlobalTeamID: 11,
    HeadCoach: "Dan Campbell",
    PrimaryColor: "0076B6",
    SecondaryColor: "B0B7BC",
    TertiaryColor: null,
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/2/26/Detroit_Lions_wordmark.svg",
    OffensiveCoordinator: "Ben Johnson",
    DefensiveCoordinator: "Aaron Glenn",
    SpecialTeamsCoach: "Dave Fipp",
    OffensiveScheme: "3WR",
    DefensiveScheme: "4-3"
  },
  {
    Key: "GB",
    TeamID: 12,
    PlayerID: 12,
    City: "Green Bay",
    Name: "Packers",
    Conference: "NFC",
    Division: "North",
    FullName: "Green Bay Packers",
    StadiumID: 22,
    ByeWeek: 6,
    GlobalTeamID: 12,
    HeadCoach: "Matt LaFleur",
    PrimaryColor: "203731",
    SecondaryColor: "FFB612",
    TertiaryColor: "FFFFFF",
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/1/17/Green_Bay_Packers_wordmark.svg",
    OffensiveCoordinator: "Adam Stenavich",
    DefensiveCoordinator: "Joe Barry",
    SpecialTeamsCoach: "Rich Bisaccia",
    OffensiveScheme: "3WR",
    DefensiveScheme: "3-4"
  },
  {
    Key: "HOU",
    TeamID: 13,
    PlayerID: 13,
    City: "Houston",
    Name: "Texans",
    Conference: "AFC",
    Division: "South",
    FullName: "Houston Texans",
    StadiumID: 11,
    ByeWeek: 7,
    GlobalTeamID: 13,
    HeadCoach: "DeMeco Ryans",
    PrimaryColor: "03202F",
    SecondaryColor: "A71930",
    TertiaryColor: "FFFFFF",
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Houston_Texans_wordmark.svg",
    OffensiveCoordinator: "Bobby Slowik",
    DefensiveCoordinator: "Matt Burke",
    SpecialTeamsCoach: "Frank Ross",
    OffensiveScheme: "3WR",
    DefensiveScheme: "4-3"
  },
  {
    Key: "IND",
    TeamID: 14,
    PlayerID: 14,
    City: "Indianapolis",
    Name: "Colts",
    Conference: "AFC",
    Division: "South",
    FullName: "Indianapolis Colts",
    StadiumID: 9,
    ByeWeek: 11,
    GlobalTeamID: 14,
    HeadCoach: "Shane Steichen",
    PrimaryColor: "013369",
    SecondaryColor: "FFFFFF",
    TertiaryColor: "A5ACAF",
    QuaternaryColor: "1D252C",
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/5/58/Indianapolis_Colts_new_wordmark.svg",
    OffensiveCoordinator: "Jim Bob Cooter",
    DefensiveCoordinator: "Gus Bradley",
    SpecialTeamsCoach: "Brian Mason",
    OffensiveScheme: "3WR",
    DefensiveScheme: "4-3"
  },
  {
    Key: "JAX",
    TeamID: 15,
    PlayerID: 52,
    City: "Jacksonville",
    Name: "Jaguars",
    Conference: "AFC",
    Division: "South",
    FullName: "Jacksonville Jaguars",
    StadiumID: 10,
    ByeWeek: 9,
    GlobalTeamID: 15,
    HeadCoach: "Doug Pederson",
    PrimaryColor: "006778",
    SecondaryColor: "000000",
    TertiaryColor: "9F792C",
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Jacksonville_Jaguars_wordmark.svg",
    OffensiveCoordinator: "Press Taylor",
    DefensiveCoordinator: "Mike Caldwell",
    SpecialTeamsCoach: "Heath Farwell",
    OffensiveScheme: "3WR",
    DefensiveScheme: "3-4"
  },
  {
    Key: "KC",
    TeamID: 16,
    PlayerID: 55,
    City: "Kansas City",
    Name: "Chiefs",
    Conference: "AFC",
    Division: "West",
    FullName: "Kansas City Chiefs",
    StadiumID: 15,
    ByeWeek: 10,
    GlobalTeamID: 16,
    HeadCoach: "Andy Reid",
    PrimaryColor: "E31837",
    SecondaryColor: "FFB612",
    TertiaryColor: "FFFFFF",
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/7/79/Kansas_City_Chiefs_wordmark.svg",
    OffensiveCoordinator: "Matt Nagy",
    DefensiveCoordinator: "Steve Spagnuolo",
    SpecialTeamsCoach: "Dave Toub",
    OffensiveScheme: "3WR",
    DefensiveScheme: "4-3"
  },
  {
    Key: "LAC",
    TeamID: 29,
    PlayerID: 84,
    City: "Los Angeles",
    Name: "Chargers",
    Conference: "AFC",
    Division: "West",
    FullName: "Los Angeles Chargers",
    StadiumID: 54,
    ByeWeek: 5,
    GlobalTeamID: 29,
    HeadCoach: "Brandon Staley",
    PrimaryColor: "0080C6",
    SecondaryColor: "FFC20E",
    TertiaryColor: "FFFFFF",
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/a/a6/Los_Angeles_Chargers_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Los_Angeles_Chargers_2020_wordmark.svg",
    OffensiveCoordinator: "Kellen Moore",
    DefensiveCoordinator: "Derrick Ansley",
    SpecialTeamsCoach: "Ryan Ficken",
    OffensiveScheme: "3WR",
    DefensiveScheme: "3-4"
  },
  {
    Key: "LAR",
    TeamID: 32,
    PlayerID: 32,
    City: "Los Angeles",
    Name: "Rams",
    Conference: "NFC",
    Division: "West",
    FullName: "Los Angeles Rams",
    StadiumID: 54,
    ByeWeek: 10,
    GlobalTeamID: 32,
    HeadCoach: "Sean McVay",
    PrimaryColor: "003594",
    SecondaryColor: "FFD100",
    TertiaryColor: null,
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/8/8a/Los_Angeles_Rams_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/7/7e/LA_Rams_wordmark.svg",
    OffensiveCoordinator: "Mike LaFleur",
    DefensiveCoordinator: "Raheem Morris",
    SpecialTeamsCoach: "Chase Blackburn",
    OffensiveScheme: "3WR",
    DefensiveScheme: "3-4"
  },
  {
    Key: "LV",
    TeamID: 25,
    PlayerID: 83,
    City: "Las Vegas",
    Name: "Raiders",
    Conference: "AFC",
    Division: "West",
    FullName: "Las Vegas Raiders",
    StadiumID: 53,
    ByeWeek: 13,
    GlobalTeamID: 25,
    HeadCoach: "Josh McDaniels",
    PrimaryColor: "A5ACAF",
    SecondaryColor: "000000",
    TertiaryColor: null,
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/4/48/Las_Vegas_Raiders_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/5/51/Las_Vegas_Raiders_wordmark.svg",
    OffensiveCoordinator: "Mick Lombardi",
    DefensiveCoordinator: "Patrick Graham",
    SpecialTeamsCoach: "Tom McMahon",
    OffensiveScheme: "3WR",
    DefensiveScheme: "4-3"
  },
  {
    Key: "MIA",
    TeamID: 19,
    PlayerID: 64,
    City: "Miami",
    Name: "Dolphins",
    Conference: "AFC",
    Division: "East",
    FullName: "Miami Dolphins",
    StadiumID: 2,
    ByeWeek: 10,
    GlobalTeamID: 19,
    HeadCoach: "Mike McDaniel",
    PrimaryColor: "008E97",
    SecondaryColor: "FC4C02",
    TertiaryColor: "FFFFFF",
    QuaternaryColor: "005778",
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/3/37/Miami_Dolphins_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/0/09/Dolphins_textlogo13.png",
    OffensiveCoordinator: "Frank Smith",
    DefensiveCoordinator: "Vic Fangio",
    SpecialTeamsCoach: "Danny Crossman",
    OffensiveScheme: "3WR",
    DefensiveScheme: "3-4"
  },
  {
    Key: "MIN",
    TeamID: 20,
    PlayerID: 67,
    City: "Minnesota",
    Name: "Vikings",
    Conference: "NFC",
    Division: "North",
    FullName: "Minnesota Vikings",
    StadiumID: 42,
    ByeWeek: 13,
    GlobalTeamID: 20,
    HeadCoach: "Kevin O'Connell",
    PrimaryColor: "4F2683",
    SecondaryColor: "FFC62F",
    TertiaryColor: "FFFFFF",
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Minnesota_Vikings_wordmark.svg",
    OffensiveCoordinator: "Wes Phillips",
    DefensiveCoordinator: "Brian Flores",
    SpecialTeamsCoach: "Matt Daniels",
    OffensiveScheme: "3WR",
    DefensiveScheme: "3-4"
  },
  {
    Key: "NE",
    TeamID: 21,
    PlayerID: 21,
    City: "New England",
    Name: "Patriots",
    Conference: "AFC",
    Division: "East",
    FullName: "New England Patriots",
    StadiumID: 4,
    ByeWeek: 11,
    GlobalTeamID: 21,
    HeadCoach: "Bill Belichick",
    PrimaryColor: "002244",
    SecondaryColor: "C60C30",
    TertiaryColor: "B0B7BC",
    QuaternaryColor: "FFFFFF",
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/f/f5/New_England_Patriots_wordmark.svg",
    OffensiveCoordinator: "Bill O'Brien",
    DefensiveCoordinator: null,
    SpecialTeamsCoach: "Cameron Achord",
    OffensiveScheme: "3WR",
    DefensiveScheme: "3-4"
  },
  {
    Key: "NO",
    TeamID: 22,
    PlayerID: 69,
    City: "New Orleans",
    Name: "Saints",
    Conference: "NFC",
    Division: "South",
    FullName: "New Orleans Saints",
    StadiumID: 27,
    ByeWeek: 11,
    GlobalTeamID: 22,
    HeadCoach: "Dennis Allen",
    PrimaryColor: "D3BC8D",
    SecondaryColor: "000000",
    TertiaryColor: "FFFFFF",
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/1/10/New_Orleans_Saints_first_wordmark.png",
    OffensiveCoordinator: "Pete Carmichael",
    DefensiveCoordinator: "Joe Woods",
    SpecialTeamsCoach: "Darren Rizzi",
    OffensiveScheme: "3WR",
    DefensiveScheme: "4-3"
  },
  {
    Key: "NYG",
    TeamID: 23,
    PlayerID: 75,
    City: "New York",
    Name: "Giants",
    Conference: "NFC",
    Division: "East",
    FullName: "New York Giants",
    StadiumID: 3,
    ByeWeek: 13,
    GlobalTeamID: 23,
    HeadCoach: "Brain Daboll",
    PrimaryColor: "0B2265",
    SecondaryColor: "A71930",
    TertiaryColor: "FFFFFF",
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Nygiants_textlogo.png",
    OffensiveCoordinator: "Mike Kafka",
    DefensiveCoordinator: "Don Martindale",
    SpecialTeamsCoach: "Thomas McGaughey",
    OffensiveScheme: "3WR",
    DefensiveScheme: "3-4"
  },
  {
    Key: "NYJ",
    TeamID: 24,
    PlayerID: 82,
    City: "New York",
    Name: "Jets",
    Conference: "AFC",
    Division: "East",
    FullName: "New York Jets",
    StadiumID: 3,
    ByeWeek: 7,
    GlobalTeamID: 24,
    HeadCoach: "Robert Saleh",
    PrimaryColor: "115740",
    SecondaryColor: "FFFFFF",
    TertiaryColor: "000000",
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/New_York_Jets_wordmark.svg",
    OffensiveCoordinator: "Nathaniel Hackett",
    DefensiveCoordinator: "Jeff Ulbrich",
    SpecialTeamsCoach: "Brant Boyer",
    OffensiveScheme: "3WR",
    DefensiveScheme: "4-3"
  },
  {
    Key: "PHI",
    TeamID: 26,
    PlayerID: 26,
    City: "Philadelphia",
    Name: "Eagles",
    Conference: "NFC",
    Division: "East",
    FullName: "Philadelphia Eagles",
    StadiumID: 18,
    ByeWeek: 10,
    GlobalTeamID: 26,
    HeadCoach: "Nick Sirianni",
    PrimaryColor: "004851",
    SecondaryColor: "A2AAAD",
    TertiaryColor: "000000",
    QuaternaryColor: "FFFFFF",
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Eagles_New_Wordmark_2022-present.png",
    OffensiveCoordinator: "Brian Johnson",
    DefensiveCoordinator: "Sean Desai",
    SpecialTeamsCoach: "Michael Clay",
    OffensiveScheme: "3WR",
    DefensiveScheme: "4-3"
  },
  {
    Key: "PIT",
    TeamID: 28,
    PlayerID: 28,
    City: "Pittsburgh",
    Name: "Steelers",
    Conference: "AFC",
    Division: "North",
    FullName: "Pittsburgh Steelers",
    StadiumID: 8,
    ByeWeek: 6,
    GlobalTeamID: 28,
    HeadCoach: "Mike Tomlin",
    PrimaryColor: "000000",
    SecondaryColor: "FFB612",
    TertiaryColor: null,
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/9/92/Pittsburgh_Steelers_Script.svg",
    OffensiveCoordinator: "Matt Canada",
    DefensiveCoordinator: "Teryl Austin",
    SpecialTeamsCoach: "Danny Smith",
    OffensiveScheme: "3WR",
    DefensiveScheme: "3-4"
  },
  {
    Key: "SEA",
    TeamID: 30,
    PlayerID: 90,
    City: "Seattle",
    Name: "Seahawks",
    Conference: "NFC",
    Division: "West",
    FullName: "Seattle Seahawks",
    StadiumID: 31,
    ByeWeek: 5,
    GlobalTeamID: 30,
    HeadCoach: "Pete Carroll",
    PrimaryColor: "002244",
    SecondaryColor: "69BE28",
    TertiaryColor: "A5ACAF",
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/d/df/Seattle_Seahawks_wordmark.svg",
    OffensiveCoordinator: "Shane Waldron",
    DefensiveCoordinator: "Clint Hurtt",
    SpecialTeamsCoach: "Larry Izzo",
    OffensiveScheme: "3WR",
    DefensiveScheme: "4-3"
  },
  {
    Key: "SF",
    TeamID: 31,
    PlayerID: 93,
    City: "San Francisco",
    Name: "49ers",
    Conference: "NFC",
    Division: "West",
    FullName: "San Francisco 49ers",
    StadiumID: 37,
    ByeWeek: 9,
    GlobalTeamID: 31,
    HeadCoach: "Kyle Shanahan",
    PrimaryColor: "AA0000",
    SecondaryColor: "B3995D",
    TertiaryColor: "FFFFFF",
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/2/24/San_Francisco_49ers_wordmark.svg",
    OffensiveCoordinator: null,
    DefensiveCoordinator: "Steve Wilks",
    SpecialTeamsCoach: "Brian Schneider",
    OffensiveScheme: "3WR",
    DefensiveScheme: "4-3"
  },
  {
    Key: "TB",
    TeamID: 33,
    PlayerID: 95,
    City: "Tampa Bay",
    Name: "Buccaneers",
    Conference: "NFC",
    Division: "South",
    FullName: "Tampa Bay Buccaneers",
    StadiumID: 24,
    ByeWeek: 5,
    GlobalTeamID: 33,
    HeadCoach: "Todd Bowles",
    PrimaryColor: "A71930",
    SecondaryColor: "322F2B",
    TertiaryColor: "DC4405",
    QuaternaryColor: "000000",
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Tampa_Bay_Buccaneers_wordmark.svg",
    OffensiveCoordinator: "Dave Canales",
    DefensiveCoordinator: "Kacy Rodgers & Larry Foote",
    SpecialTeamsCoach: "Keith Armstrong",
    OffensiveScheme: "3WR",
    DefensiveScheme: "3-4"
  },
  {
    Key: "TEN",
    TeamID: 34,
    PlayerID: 34,
    City: "Tennessee",
    Name: "Titans",
    Conference: "AFC",
    Division: "South",
    FullName: "Tennessee Titans",
    StadiumID: 12,
    ByeWeek: 7,
    GlobalTeamID: 34,
    HeadCoach: "Mike Vrabel",
    PrimaryColor: "002244",
    SecondaryColor: "4B92DB",
    TertiaryColor: "C60C30",
    QuaternaryColor: "A5ACAF",
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/7/75/Tennessee_Titans_wordmark%2C_2018.svg",
    OffensiveCoordinator: "Tim Kelly",
    DefensiveCoordinator: "Shane Bowen",
    SpecialTeamsCoach: "Craig Aukerman",
    OffensiveScheme: "3WR",
    DefensiveScheme: "3-4"
  },
  {
    Key: "WAS",
    TeamID: 35,
    PlayerID: 97,
    City: "Washington",
    Name: "Commanders",
    Conference: "NFC",
    Division: "East",
    FullName: "Washington Commanders",
    StadiumID: 19,
    ByeWeek: 14,
    GlobalTeamID: 35,
    HeadCoach: "Ron Rivera",
    PrimaryColor: "5A1414",
    SecondaryColor: "FFB612",
    TertiaryColor: "FFFFFF",
    QuaternaryColor: null,
    WikipediaLogoURL: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Washington_Commanders_logo.svg",
    WikipediaWordMarkURL: "https://upload.wikimedia.org/wikipedia/commons/7/76/Washingtoncommanders_wordmark.svg",
    OffensiveCoordinator: "Eric Bieniemy",
    DefensiveCoordinator: "Jack Del Rio",
    SpecialTeamsCoach: "Nate Kaczor",
    OffensiveScheme: "3WR",
    DefensiveScheme: "4-3"
  }
];

console.log(teams);

console.log(
  `NFC North`,
  teams.filter((obj) => obj.Conference === "NFC" && obj.Division === "North")
);
console.log(
  `NFC South`,
  teams.filter((obj) => obj.Conference === "NFC" && obj.Division === "South")
);
console.log(
  `NFC East`,
  teams.filter((obj) => obj.Conference === "NFC" && obj.Division === "East")
);
console.log(
  `NFC West`,
  teams.filter((obj) => obj.Conference === "NFC" && obj.Division === "West")
);
console.log(
  `AFC North`,
  teams.filter((obj) => obj.Conference === "AFC" && obj.Division === "North")
);
console.log(
  `AFC South`,
  teams.filter((obj) => obj.Conference === "AFC" && obj.Division === "South")
);
console.log(
  `AFC East`,
  teams.filter((obj) => obj.Conference === "AFC" && obj.Division === "East")
);
console.log(
  `AFC West`,
  teams.filter((obj) => obj.Conference === "AFC" && obj.Division === "West")
);

const explorePlayers = document.querySelector(".team-stats-data");
const infoCardsSection = document.querySelector(".info-cards");
console.log(explorePlayers);

explorePlayers.addEventListener("click", function () {
  infoCardsSection.classList.remove("hidden");
  infoCardsSection.scrollIntoView({ behavior: "smooth" });
  // window.open("./teamStatsInformation/index.html", "_blank");
});

const teamsTable = document.querySelector(".teams-table");
teamsTable.addEventListener("click", function (e) {
  console.log(e.target);
});
